### ISSUE TITLE
Unable to save setting in EE 2.8+

### ISSUE THREAD

**Issue by builtbymonkey** [electricfunction/membrr#11]
When trying to save settings in EE 2.8+ I get redirected to the CP home does any one have a solution yet I believe it's down to the new admin url structure.

**Comment by esotm** [comment]
Was the pull ever submitted?

**Comment by pstoute** [comment]
Any update on this? Using 2.10.1 and the latest pull from this afternoon. 

Unable to use any of the forms in the membrr settings areas. I can get things to save using phpMyAdmin, but this wouldn't be a long term solution.

**Comment by brockf** [comment]
Hi all -

I've just pushed a patch to this repo that fixes this problem with admin URLs.
