### ISSUE TITLE
Member cancel tag

### ISSUE THREAD

**Issue by seyonk** [electricfunction/membrr#15]
Could someone please advise me how to create a form in membrr, for a user to cancel his subscription?
The following tag from the documentation does't seem to do anything?
{exp:membrr:cancel id="{segment_3}"}
{if cancelled}Your subscription was cancelled!{/if}
{if failure}Subscription could not be cancelled.{/if}
{/exp:membrr:cancel} 

Thank you.
Seyon.

**Comment by brockf** [comment]
This tag will work, but only if you pass the subscription ID as part of segment 3 in the URL.

**Comment by seyonk** [comment]
Thank you Brock.

However my design didn't allow me to pass the segment id in the url.

Instead I used the following code which worked for me.

{exp:membrr:subscriptions status="active" parse="inward"}
{exp:membrr:cancel id="{subscription_id}"}
{if cancelled}
<p>Your subscription has been sucessfully cancelled.</p>
{/if}
{if failure}
<p> Your subscription has not been cancelled yet.</p>
{/if}
{/exp:membrr:cancel}
{/exp:membrr:subscriptions}

**Comment by seyonk** [comment]
Thank you very much for your time Brock.
However my design didn't allow me to pass the segment id in the url.Instead I used the following code which worked for me.
{exp:membrr:subscriptions status="active" parse="inward"}
{exp:membrr:cancel id="{subscription_id}"}
{if cancelled}<p>Your subscription has been sucessfully cancelled.</p>{/if}
{if failure}<p> Your subscription has not been cancelled yet.</p>{/if}
{/exp:membrr:cancel}
{/exp:membrr:subscriptions} 
Kind Regards,
Seyon Kiriyadoss. 

     On Sunday, January 4, 2015 5:40 PM, Brock Ferguson <notifications@github.com> wrote:
   

 Closed #15.—
